[package]
name = "para-lipics"
version = "0.1.1"
entrypoint = "lib.typ"
authors = ["Nicolas M", "Timothé A"]
license = "MIT"
description = "Unofficial Dagstuhl LIPIcs template."
repository = "https://github.com/para-lipics/para-lipics/"
keywords = ["LIPIcs", "Dagstuhl"]
categories = ["paper"]
disciplines = ["computer-science", "mathematics"]
compiler = "0.13.0"
exclude = ["other/", "test-doc.pdf"]

[template]
path = "template"
entrypoint = "sample-article.typ"
thumbnail = "thumbnail.png"